---
# tasks file for lamp
# This task installs and enables apache on webservers
- name: ensure apache, php related packages are installed
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - php
    - php-mysql
- name: ensure apache is running
  service: name=httpd state=running enabled=yes
- name: copy files to document root
  copy: src=penclchk.gif dest=/var/www/html/penclchk.gif
- name: copy application code to document root
  template: src=index.php.j2 dest=/var/www/html/index.php
  notify: start httpd
